name: CI/CD Pipeline - Aplicación

on:
  push:
    branches:
      - pipeline-setup

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::509399606070:role/githubactiontoaws #BA
        aws-region: us-east-2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./VirtualAccount
        push: true
        tags: ghcr.io/abrachos/virtualaccount:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Install kubectl 1.32.0 
      run: | 
        curl -LO "https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl" 
        chmod +x kubectl 
        sudo mv kubectl /usr/local/bin/ 
      
    - name: Install aws-cli 2.22.33 
      run: | 
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.2.33.zip" -o "awscliv2.zip" 
        unzip awscliv2.zip 
        sudo ./aws/install --update
        aws --version # Verificación1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Verify kubectl version 
      run: kubectl version --client 
    
    - name: Verify awscli version 
      run: aws --version

    - name: Create .kube directory
      run: |
        mkdir -p $HOME/.kube

    - name: Get EKS Token and update Kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-2 --name virtualaccount-cluster
        export KUBECONFIG=$HOME/.kube/config
        #sed -i '/args:/a\ interactiveMode: IfAvailable' $HOME/.kube/config
        sed -i '/- --output/a\ \ \ \ \ \ \ \ - json\n\ \ \ \ \ \ \ \ interactiveMode: IfAvailable' $HOME/.kube/config
        sed -i 's/client.authentication.k8s.io\/v1alpha1/client.authentication.k8s.io\/v1/g' $HOME/.kube/config 
        sed -i 's/client.authentication.k8s.io\/v1beta1/client.authentication.k8s.io\/v1/g' $HOME/.kube/config
        cat $HOME/.kube/config

    - name: Validate Kubeconfig
      run: |
        kubectl config get-contexts
        kubectl config current-context
        kubectl cluster-info
        kubectl get nodes
        
    - name: Use specific kubeconfig context 
      run: | 
        kubectl config use-context arn:aws:eks:us-east-2:509399606070:cluster/virtualaccount-cluster

    - name: Verify Access
      run: |
        kubectl get namespaces

    - name: Debug kubeconfig
      run: |
        kubectl cluster-info
        kubectl config view
        kubectl config get-contexts 
        kubectl config current-context
        kubectl get nodes

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: $HOME/.kube/config
      run: |
        kubectl apply --validate=false -f kubernetes/deployment.yaml
        kubectl apply --validate=false -f kubernetes/service.yaml

    - name: Set output
      run: echo "DEPLOY_STATUS=success" >> $GITHUB_ENV

    - name: Display output
      run: echo "The deployment status is ${{ env.DEPLOY_STATUS }}"
